// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxhEw',
    appId: '1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx6',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: '+flutter-ccccccccc-xxxxxxxxxxxxxxxxxx',
    authDomain: 'flutter-xxxxxxxxxxxxxxxxxx.firebaseapp.com',
    storageBucket: 'flutter-xxxxxxxxxxxxxxxxxxxx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxxxxxxxxxxxxxxx:android:xxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'flutter-ccccccccc-xxxxxxxxxxxxxxxx',
    storageBucket: 'flutter-xxxxxxxxxxxx-xxxxxxxxxxxxxx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxxxxx:ios:ccxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxx',
    projectId: 'flutter-ccccccccc-ccxxxxxxxxxxx',
    storageBucket: 'flutter-ccccccccc-ccxxxxxxxxxxx.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxxxxx:ios:ccxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxx',
    projectId: 'flutter-ccccccccc-ccxxxxxxxxxxx',
    storageBucket: 'flutter-ccccccccc-ccxxxxxxxxxxx.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJn-xxxxxxxxxxxxxxxxx--xxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxxxxx:web:xxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxx',
    projectId: 'flutter-ccccccccc-ccxxxxxxxxxxx',
    authDomain: 'flutter-ccccccccc-ccxxxxxxxxxxx.firebaseapp.com',
    storageBucket: 'flutter-ccccccccc-ccxxxxxxxxxxx.firebasestorage.app',
  );

}
