// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJn-RflznQFZW5Kph--Ikuv5Vnpp6IhEw',
    appId: '1:76171508099:web:da22a720fa6b671d3a1eb6',
    messagingSenderId: '76171508099',
    projectId: '+flutter-project-ab3f0',
    authDomain: 'flutter-project-ab3f0.firebaseapp.com',
    storageBucket: 'flutter-project-ab3f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevxdR-F7_M9k5aeY3GXb3yMkWqOebDxo',
    appId: '1:76171508099:android:436d40498fca1af33a1eb6',
    messagingSenderId: '76171508099',
    projectId: 'flutter-project-ab3f0',
    storageBucket: 'flutter-project-ab3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3U8zPG84ZOe1357upqrVHjFMnR6Wuiug',
    appId: '1:76171508099:ios:4a4768a3ffbc6d803a1eb6',
    messagingSenderId: '76171508099',
    projectId: 'flutter-project-ab3f0',
    storageBucket: 'flutter-project-ab3f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3U8zPG84ZOe1357upqrVHjFMnR6Wuiug',
    appId: '1:76171508099:ios:4a4768a3ffbc6d803a1eb6',
    messagingSenderId: '76171508099',
    projectId: 'flutter-project-ab3f0',
    storageBucket: 'flutter-project-ab3f0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJn-RflznQFZW5Kph--Ikuv5Vnpp6IhEw',
    appId: '1:76171508099:web:dfed4ec80e89f5f33a1eb6',
    messagingSenderId: '76171508099',
    projectId: 'flutter-project-ab3f0',
    authDomain: 'flutter-project-ab3f0.firebaseapp.com',
    storageBucket: 'flutter-project-ab3f0.firebasestorage.app',
  );

}